application: erhs-team53
version: 6-1-3
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
 
- url: /css
  static_dir: src/css
  
- url: /files
  static_dir: files

- url: /images
  static_dir: images

- url: /lib
  static_dir: src/libraries
  
- url: /js
  static_dir: src/js
  
- url: /favicon.ico
  static_files: images/logo/favicon.png
  upload: images/logo/favicon.png

- url: .*
  script: src.py.main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
