application: erhs-team53
version: 5-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
 
- url: /css
  static_dir: css

- url: /res
  static_dir: js

- url: /yui
  static_dir: yui
  
- url: /files
  static_dir: files

- url: /images
  static_dir: images

- url: /fancybox
  static_dir: fancybox
  
- url: /js
  static_dir: js
  
- url: /favicon.ico
  static_files: images/logo/favicon.png
  upload: images/logo/favicon.png

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
